import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const Jetbrains_mono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Jetbrains_mono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
