export const myProjects = [
  {
    id: 1,
    title: "MERN E-commerce App",
    description:
      "🚀 MERN E-commerce App with Tailwind CSS UI, Framer Motion animations & GSAP scroll effects.",
    subDescription: [
      "Developed using MERN stack with TailwindCSS for modern UI design.",
      "Integrated GSAP and Framer Motion for smooth animations and scroll effects.",
      "Implemented authentication with OAuth and JWT for secure login.",
      "Built scalable backend APIs with Node.js and Express.js.",
    ],
    href: "",
    logo: "",
    image: "/assets/work/photo-e-commerce-store.png",
    tags: [
      { id: 1, name: "Node.js", path: "/assets/logos/nodejs.svg" },
      { id: 2, name: "Express.js", path: "/assets/logos/express.svg" },
      { id: 3, name: "React.js", path: "/assets/logos/react.svg" },
      { id: 4, name: "TailwindCSS", path: "/assets/logos/tailwindcss.svg" },
      { id: 5, name: "MongoDB", path: "/assets/logos/mongodb.svg" },
      { id: 6, name: "OAuth", path: "/assets/logos/oauth.svg" },
      { id: 7, name: "JWT", path: "/assets/logos/jwt.svg" },
    ],
    github: "https://github.com/elishabhatti/e-commerce-with-mern.git",
  },
  {
    id: 2,
    title: "Full Stack Blog App",
    description:
      "Developed a robust backend using Node.js and Express.js, implementing secure RESTful APIs to handle blog post CRUD operations, user authentication, and data validation with integration to a MongoDB database.",
    subDescription: [
      "Created blog CRUD system with secure REST APIs.",
      "Implemented user authentication using OAuth and JWT.",
      "Integrated MongoDB for data storage and validation.",
      "Built frontend with React.js and TailwindCSS.",
    ],
    href: "",
    logo: "",
    image: "/assets/work/photo-blog-app.png",
    tags: [
      { id: 1, name: "Node.js", path: "/assets/logos/nodejs.svg" },
      { id: 2, name: "Express.js", path: "/assets/logos/express.svg" },
      { id: 3, name: "React.js", path: "/assets/logos/react.svg" },
      { id: 4, name: "TailwindCSS", path: "/assets/logos/tailwindcss.svg" },
      { id: 5, name: "MongoDB", path: "/assets/logos/mongodb.svg" },
      { id: 6, name: "OAuth", path: "/assets/logos/oauth.svg" },
      { id: 7, name: "JWT", path: "/assets/logos/jwt.svg" },
    ],
    github: "https://github.com/elishabhatti/server-of-the-blog-app.git",
  },
  {
    id: 3,
    title: "URL Shortener",
    description:
      "Built a full-featured URL shortener application with a robust backend and secure authentication system.",
    subDescription: [
      "Developed backend with Node.js and Express.js.",
      "Implemented authentication with OAuth.",
      "Used MySQL for storing shortened URLs and user data.",
      "Built frontend with EJS templates for server-side rendering.",
    ],
    href: "",
    logo: "",
    image: "/assets/work/photo-url-shortener.png",
    tags: [
      { id: 1, name: "Node.js", path: "/assets/logos/nodejs.svg" },
      { id: 2, name: "Express.js", path: "/assets/logos/express.svg" },
      { id: 3, name: "EJS", path: "/assets/logos/ejs.svg" },
      { id: 4, name: "MySQL", path: "/assets/logos/mysql.svg" },
      { id: 5, name: "OAuth", path: "/assets/logos/oauth.svg" },
    ],
    github: "https://github.com/elishabhatti/url-shortener.git",
  },
  {
    id: 4,
    title: "Task Management App",
    description: "Created a Task Management App with Redux Toolkit.",
    subDescription: [
      "Built with React.js and Redux Toolkit for state management.",
      "Implemented responsive UI using TailwindCSS.",
      "Users can add, edit, delete, and track tasks efficiently.",
      "Deployed live on Vercel.",
    ],
    href: "https://redux-toolkit-todo-silk.vercel.app/",
    logo: "",
    image: "/assets/work/photo-todo-horizon.png",
    tags: [
      { id: 1, name: "React.js", path: "/assets/logos/react.svg" },
      { id: 2, name: "TailwindCSS", path: "/assets/logos/tailwindcss.svg" },
      { id: 3, name: "Redux Toolkit", path: "/assets/logos/redux.svg" },
    ],
    github: "https://github.com/elishabhatti/redux-toolkit-todo.git",
  },
];

